### ISSUE TITLE
视频的目标检测结果没办法打开

### ISSUE THREAD

**Issue by jpyjpr** [bubbliiiing/retinanet-keras#22]
我是在远程docker容器中运行的，mode=video, 但是检测结束后保存的视频没办法查看，检测过程也没有报错，这是什么问题呢？
elif mode == "video":
        capture = cv2.VideoCapture(video_path)
        if video_save_path!="":
            fourcc  = cv2.VideoWriter_fourcc(*'XVID')
         
            size    = (int(capture.get(cv2.CAP_PROP_FRAME_WIDTH)), int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
            out     = cv2.VideoWriter(video_save_path, fourcc, video_fps, size)

        ref, frame = capture.read()
        if not ref:
            raise ValueError("未能正确读取摄像头（视频），请注意是否正确安装摄像头（是否正确填写视频路径）。")

        fps = 0.0
        frame_num = 20
        while(True):
            t1 = time.time()
            # 读取某一帧
            ref, frame = capture.read()
            print(ref)
            if not ref:
                break
            # 格式转变，BGRtoRGB
            frame = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
            # 转变成Image
            frame = Image.fromarray(np.uint8(frame))
            # 进行检测
            frame = np.array(retinanet.detect_image(frame))
            # RGBtoBGR满足opencv显示格式
            frame = cv2.cvtColor(frame,cv2.COLOR_RGB2BGR)
            
            fps  = ( fps + (1./(time.time()-t1)) ) / 2
            print("fps= %.2f"%(fps))
            frame = cv2.putText(frame, "fps= %.2f"%(fps), (0, 40), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
            
            while(frame_num<=25):
                cv2.imwrite(f'frame_{frame_num}.jpg', frame)

                frame_num += 1
            # cv2.imshow("video",frame)
            # c= cv2.waitKey(1) & 0xff 
            # if video_save_path!="":
            #     out.write(frame)

            # if c==27:
            #     capture.release()
            #     break

        print("Video Detection Done!")
        capture.release()
        if video_save_path!="":
            print("Save processed video to the path :" + video_save_path)
            out.write(frame)
            out.release()
        # cv2.destroyAllWindows()

**Comment by strWuYaoJu** [comment]
谢谢你的来信！

**Comment by bubbliiiing** [comment]
是播放器的问题吗？

**Comment by jpyjpr** [comment]
> 是播放器的问题吗？

播放器没问题，是帧的写入我弄错了，已经解决啦~ 感谢感谢！！

**Comment by bubbliiiing** [comment]
OKOK
